patrimonio/urls.py
# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import patterns


urlpatterns = patterns('patrimonio.views',
                       #     (r'escolhe_termo$', 'ajax_escolhe_termo'),
                       #    (r'escolhe_protocolo$', 'ajax_escolhe_protocolo'),
                       (r'escolhe_pagamento$', 'ajax_escolhe_pagamento'),
                       (r'escolhe_entidade$', 'ajax_escolhe_entidade'),
                       (r'escolhe_patrimonio$', 'ajax_escolhe_patrimonio'),
                       (r'escolhe_equipamento$', 'ajax_escolhe_equipamento'),
                       #    (r'escolhe_detalhe$', 'ajax_escolhe_detalhe'),
                       (r'filtra_pn_estado$', 'ajax_filtra_pn_estado'),
                       #    (r'patrimonio_existente$', 'ajax_patrimonio_existente'),
                       (r'relatorio/por_estado$', 'por_estado'),

                       (r'relatorio/por_tipo$', 'por_tipo'),
                       (r'relatorio/por_tipo/$', 'por_tipo'),

                       (r'relatorio/por_tipo_consignado$', 'por_tipo_consignado'),
                       (r'relatorio/por_tipo_consignado/$', 'por_tipo_consignado'),

                       (r'relatorio/por_marca$', 'por_marca'),
                       (r'relatorio/por_marca/(?P<pdf>\d)$', 'por_marca'),
                       (r'relatorio/por_local$', 'por_local'),
                       (r'relatorio/por_local/(?P<pdf>\d)$', 'por_local'),
                       (r'relatorio/por_local_termo$', 'por_local_termo'),
                       (r'relatorio/por_local_termo/(?P<pdf>\d)$', 'por_local_termo'),
                       (r'relatorio/por_local_rack$', 'por_local_rack'),
                       (r'relatorio/por_local_rack/(?P<pdf>\d)$', 'por_local_rack'),
                       (r'relatorio/por_termo$', 'por_termo'),
                       (r'relatorio/por_termo/(?P<pdf>\d)$', 'por_termo'),
                       (r'relatorio/por_tipo_equipamento$', 'por_tipo_equipamento'),
                       (r'relatorio/por_tipo_equipamento2$', 'por_tipo_equipamento2'),
                       (r'relatorio/presta_contas$', 'presta_contas'),
                       (r'abre_arvore$', 'ajax_abre_arvore'),
                       (r'abre_arvore_tipo$', 'ajax_abre_arvore_tipo'),
                       (r'racks$', 'racks'),
                       (r'relatorio_rack$', 'relatorio_rack'),
                       (r'patrimonio_historico$', 'ajax_patrimonio_historico'),
                       (r'ajax_get_equipamento$', 'ajax_get_equipamento'),
                       (r'ajax_get_procedencia_filter_tipo$', 'ajax_get_procedencia_filter_tipo'),
                       (r'ajax_get_marcas_por_termo$', 'ajax_get_marcas_por_termo'),
                       (r'planta_baixa_edit$', 'planta_baixa_edit'),
                       )

patrimonio/forms.py
# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

import django
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.forms.utils import ErrorList
from django.utils.html import mark_safe
from django.contrib.admin.widgets import RelatedFieldWidgetWrapper
from django.db.models.fields.related import ManyToOneRel
from django.forms.models import BaseInlineFormSet, inlineformset_factory
from django.forms.fields import ChoiceField

from utils.request_cache import get_request_cache
from financeiro.models import Pagamento
from memorando.models import MemorandoSimples
from identificacao.models import Entidade, EnderecoDetalhe
from outorga.models import Termo
from patrimonio.models import Equipamento, Patrimonio, HistoricoLocal, Estado


# Exibição de patrimonios filhos em forma de tabela, dentro do form de Patrimonio
class PatrimonioReadOnlyWidget(forms.Widget):
    def render(self, name, value, attrs=None):
        retorno = ''
        if value and len(value) > 0:
            retorno += u'<table>'
            retorno += "<tr><th>Nome</th><th>NS</th><th>Desc</th></tr>"
            if value:
                for v in value:
                    value_id = v[0] or ''
                    retorno += "<tr>"
                    retorno += "<td style='white-space:nowrap;'>" \
                               "<a href='/patrimonio/patrimonio/%s/'>%s</td>" % (value_id, v[1] or '')
                    retorno += "<td style='white-space:nowrap;'>" \
                               "<a href='/patrimonio/patrimonio/%s/'>%s</td>" % (value_id, v[2] or '')
                    retorno += "<td><a href='/patrimonio/patrimonio/%s/'>%s</td>" % (value_id, v[3] or '')
                    retorno += "</tr>"
            retorno += "</table>"
        return mark_safe(retorno)

    def _has_changed(self, initial, data):
        return False


class PatrimonioReadOnlyField(forms.FileField):
    widget = PatrimonioReadOnlyWidget

    def __init__(self, widget=None, label=None, initial=None, help_text=None):
        forms.Field.__init__(self, label=label, initial=initial, help_text=help_text, widget=widget)

    def clean(self, value, initial=None):
        self.widget.initial = initial
        return initial


class AdvancedModelChoiceIterator(forms.models.ModelChoiceIterator):
    """
    Classe para exibição da Entidade no formato Select, ordenado pelo sigla_completa
    que inclui a Entidade pai, no formato "<sigla entidade pai> - <sigla entidade>"
    """
    def __iter__(self):
        if self.field.empty_label is not None:
            yield ("", self.field.empty_label)
        else:
            yield ("", "---------")

        choices = []
        # Preenche os valores do compo com o ID, a sigla completa com a entidade pai, e a sigla tabulada
        for item in self.queryset.select_related('entidade', 'entidade__entidade'):

            label = mark_safe(item.sigla_tabulada().replace(' ', '&nbsp;'))
            sortValue = item.sigla_completa()
            choices.append((item.pk, label, sortValue))
        # Reordena os itens utilizando a sigla completa
        choices = sorted(choices, key=lambda obj: obj[2])

        for item in choices:
            yield (item[0], item[1])


class EntidadeModelChoiceField(forms.ModelChoiceField):
    def __init__(self, *args, **kwargs):
        super(EntidadeModelChoiceField, self).__init__(*args, **kwargs)

    def _get_choices(self):
        if hasattr(self, '_choices'):
            return self._choices
        # Escolhe entre o empty_label ou senão coloca um valor padrão para o item vazio
        return AdvancedModelChoiceIterator(self)

    choices = property(_get_choices, ChoiceField._set_choices)


class EquipamentoContidoModelChoiceField(forms.ModelChoiceField):
    """
    Classe para exibição de Equipamentos - contidos em.
    Restringe a exibição da descrição em 200 caracteres com a adição de reticências para não exceder a largura da tela
    """
    def label_from_instance(self, obj):
        info = (obj.__unicode__()[:200] + '..') if len(obj.__unicode__()) > 200 else obj.__unicode__()
        return u'%s' % info


class EquipamentoModelChoiceField(forms.ModelChoiceField):
    """
    Classe para exibição de Equipamentos.
    Restringe a exibição da descrição em 150 caracteres com a adição de reticências para não exceder a largura da tela
    """
    def label_from_instance(self, obj):
        info = (obj.descricao[:150] + '..') if len(obj.descricao) > 150 else obj.descricao
        return u'%s - %s' % (info, obj.part_number)


class PatrimonioAdminForm(forms.ModelForm):
    """
    Uma instância dessa classe faz algumas definições para a tela de cadastramento do modelo 'Patrimonio'.

    O método '__init__'        Define as opções do campo 'protocolo' (apenas protocolos diferentes de 'Contrato', 'OS'
     e 'Cotação'.
    O campo 'termo'        Foi criado para filtrar o campo 'protocolo'
    O campo 'protocolo'        Foi criado para filtrar o campo 'itemprotocolo'
    A class 'Meta'        Define o modelo que será utilizado.
    A class 'Media'        Define os arquivos .js que serão utilizados.
    """
    termo = forms.ModelChoiceField(Termo.objects.all(), label=_(u'Termo de outorga'), required=False,
                                   widget=forms.Select(attrs={'class': 'auxiliary'}))

    npgto = forms.CharField(label=_(u'Nº do cheque ou do documento'), required=False,
                            widget=forms.TextInput(
                                attrs={'class': 'auxiliary',
                                       'onchange': 'ajax_filter_pagamentos("/patrimonio/escolhe_pagamento", '
                                                   'this.value);'}))

#    part_number = forms.CharField(required=False, widget=forms.TextInput(
# attrs={'onchange':'ajax_patrimonio_existente(this.value);'}))

    nf = forms.CharField(label=_(u'Nº da NF ou NS'), required=False,
                         widget=forms.TextInput(attrs={'onkeydown': 'if (event.keyCode == 13) {$(\'#id_patrimonio\')'
                                                                    '.focus(); return false;}',
                                                       'onchange': 'ajax_filter_patrimonio(this.value);',
                                                       'class': 'auxiliary'}))

    tem_numero_fmusp = forms.BooleanField(label=u'Tem nº de patrimônio oficial?', required=False,
                                          widget=forms.CheckboxInput(attrs={'onchange': 'ajax_numero_fmusp();'}))

    descricao = forms.CharField(required=False, widget=forms.Textarea(attrs={'rows': '2', 'cols': '152'}))

    filtro_equipamento = forms.CharField(label=_(u'Filtro para busca de Equipamento'), required=False,
                                         widget=forms.TextInput(attrs={'onchange': 'ajax_filter_equipamento'
                                                                                   '(this.value);',
                                                                       'onkeydown': 'return false;',
                                                                       'class': 'auxiliary'}))

    # Uso de Model específico para a adição de reticências na descrição
    # e javascript para adição de link no label para a página do Equipamento selecionado
    equip_window = '<a href="#" onclick="window.open(\'/patrimonio/equipamento/\'+$(\'#id_equipamento\').val()' \
                   ' + \'/\', \'_blank\');return true;">Equipamento</a>'
    equipamento = EquipamentoModelChoiceField(queryset=Equipamento.objects.all(),
                                              required=False,
                                              label=mark_safe(equip_window),
                                              widget=forms.Select(attrs={'style': 'width:800px',
                                                                         'onchange': 'ajax_patr_form_get_equipamento'
                                                                                     '($(\'#id_equipamento\').val());',
                                                                         })
                                              )

    patrimonio_window = '<a href="#" onclick="window.open(\'/patrimonio/patrimonio/\'+' \
                        '$(\'#id_patrimonio\').val() + \'/\', \'_blank\');return true;" >Contido em</a>'
    patrimonio_historico = 'ajax_patrimonio_historico($(\'#id_patrimonio\').val());'
    patrimonio = EquipamentoContidoModelChoiceField(queryset=Patrimonio.objects.all(),
                                                    required=False,
                                                    label=mark_safe(patrimonio_window),
                                                    widget=forms.Select(attrs={'style': 'width:800px ',
                                                                               'onchange': patrimonio_historico
                                                                               }),
                                                    empty_label='---'
                                                    )

    procedencia_window = '<a href="#" onclick="window.open(\'/identificacao/entidade/\'+' \
                         '$(\'#id_entidade_procedencia\').val() + \'/\', \'_blank\');return true;">Procedência</a>'
    entidade_procedencia = EntidadeModelChoiceField(queryset=Entidade.objects.all(),
                                                    required=False,
                                                    label=mark_safe(procedencia_window),
                                                    )

    pagamento_window = '<a href="#" onclick="window.open(\'/admin/financeiro/pagamento/\'+' \

patrimonio/templates/patrimonio/conserta.html
{% extends "admin/base_site.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% load proto_tags %}
{% load i18n %}

{% block content %}
<h2>Carregar posicionamento de equipamentos a partir de um arquivo csv</h2>

{% if request.method == 'GET' %}
<form method="POST" enctype="multipart/form-data">{% csrf_token %}
    <input id="racks_id" name="racks" type="file">
    <input type="submit" value="Enviar">
</form>

{% else %}
<h4>Ok com:</h4>
<ul>
{% for l in ok %}
<li>{{ l.apelido }} {{ l }}</li>
{% endfor %}
</ul>

<h4>Falha com:</h4>
<ul>
{% for l in failed %}
<li>{{ l.apelido }} {{ l }}</li>
{% endfor %}
</ul>

{% endif %}

{% endblock %}

patrimonio/templates/patrimonio/escolhe_termo.html
{% extends "admin/base_site.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% load proto_tags %}
{% load i18n %}
{% load static from staticfiles %}
{% block extrahead %}
<style>
#form_filtro {
    display:table-row;
}
#form_filtro select {
    width: 135px;
} 

#form_filtro div {
    display:table-row;
}
#form_filtro label {
    display:table-cell;
}
#form_filtro input, 
#form_filtro select {
    display:table-cell;
    margin-left:10px;
}
#form_filtro #id_marca {
    height: 125px;
}
</style>
<script type="text/javascript" src="{% static "js/selects.js" %}"></script>
<script>
	$( document ).ready(function() {
        $( "#id_termo" ).bind("change", function() {
            ajax_get_marcas_por_termo('#id_marca', $("#id_termo").val());
        });
	});
</script>
{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">Você está em: 
      <a href="../../">{% trans "Home" %}</a> &rsaquo; 
      <a href="{% url 'patrimonio.views.por_termo' %}">Patrimônio por termo de outorga</a> &rsaquo;
    </div>
{% endblock %}
{% block content %}
    <h1>Patrimônio por termo de outorga</h1>
    <div id="div_filtro">
        <fieldset>
            <legend>Filtro</legend>
            <form method="GET" id="form_filtro">
                <div>
                	<label for="id_termo">Termo de outorga*:</label>
                	<select name="termo" id="id_termo">
                	  <option value="0">Todos</option>
                	  {% for t in filtro_termos %}
                	     <option value="{{ t.id }}">{{ t }}</option>
                	  {% endfor %}
                	</select>
                </div>
                <div>
                    <label for="id_marca">Marca</label>
                    <select name="marca" id="id_marca" multiple size=7>
                        <option value="0" selected>Todos</option>
                        {% for m in filtro_marcas %}
                           <option value="{{ m.id }}">{{ m }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div>
                	<label for="id_modalidade">Modalidade</label>
                	<select name="modalidade" id="id_modalidade">
                	    <option value="0">Todos</option>
                	    <option value="1">Material permanente</option>
                	    <option value="2">Material de consumo</option>
                	</select>
                </div>
                <div>
                	<label for="id_agilis">Têm Agilis</label>
                	<select name="agilis" id="id_agilis">
                	     <option value="-">Todos</option>
                	     <option value="0">Não</option>
                	     <option value="1">Sim</option>
                	</select>
                </div>
                <div>
                	<label for="id_doado">Doado por processo oficial</label>
                	<select name="doado" id="id_doado">
                	     <option value="2">Todos</option>
                	     <option value="0">Não doados</option>
                	     <option value="1">Doados</option>
                	</select>
                </div>
                <div>
                	<label for="id_localizado">Patrimônio localizado</label>
                	<select name="localizado" id="id_localizado">
                	     <option value="2">Todos</option>
                	     <option value="0">Não localizados</option>
                	     <option value="1">Localizados</option>
                	</select>
                </div>
                <div>
                	<label for="id_numero_fmusp">Com identificação do patrimônio oficial</label>
                	<select name="numero_fmusp" id="id_numero_fmusp">
                	     <option value="2">Todos</option>
                	     <option value="0">Não</option>
                	     <option value="1">Sim</option>
                	</select>
                </div>
                <div>
                    <label for="id_ver_numero_fmusp">Apresenta patrimônio oficial no relatório</label>
                    <input type="checkbox" name="ver_numero_fmusp" id="id_ver_numero_fmusp" checked />
                </div>
                <br />
                <div>
                    <input type="submit" value="Enviar">
                </div>
            </form>
        </fieldset>
    </div>
{% endblock %}

patrimonio/templates/patrimonio/por_termo.html
{% extends "admin/base_site.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% load proto_tags %}
{% load i18n %}
{% load static from staticfiles %}
{% block extrahead %}
<style>
#div_filtro {
	width: 750px;
	clear:both;
	margin-left:25px;
}
#form_filtro {
    display:table-row;
}
#form_filtro select {
    width: 135px;
} 

#form_filtro div {
    display:table-cell;
    padding-right:15px;
    padding-left:15px;
}
#form_filtro div div{
    display:table-row;
    
}
#form_filtro label {
    display:table-cell;
}
#form_filtro input, 
#form_filtro select {
    display:table-cell;
    margin-left:10px;
}
#form_filtro #id_marca {
}

#form_filtro #div_submit {
    vertical-align:bottom;
}

#tbl_conteudo th {
    background-color:#ddd;
    font-weight: bold;
    border-bottom:1px darkgray solid;
}
#tbl_conteudo a {
    color: inherit;
    line-height: inherit;
}
.th_nf {}
.th_descricao {}
.th_valor {}
.th_marca {}
.th_ns {}
.th_estado {}
.th_localizacao {width:445px;}
.th_posicao {}

.tr_saldo td{
    background-color:#f7f7f7;
}
</style>
<script type="text/javascript" src="{% static "js/selects.js" %}"></script>
<script>
    $( document ).ready(function() {
        $( "#id_termo" ).bind("change", function() {
            ajax_get_marcas_por_termo('#id_marca', $("#id_termo").val());
        });
    });
</script>
{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">Você está em: 
      <a href="../../">{% trans "Home" %}</a> &rsaquo; 
      <a href="{% url 'patrimonio.views.por_termo' %}">Patrimônio por termo de outorga</a>
    </div>
{% endblock %}
{% block content %}
<h1 repeat="1">Inventário da outorga {{ termo|default:'' }}</h1>

{% if termos %}
    <div id="report_toolbar">
        <form action="{% url 'patrimonio.views.por_termo' 1 %}" method="GET" id="id_form_recurso">
            <input type="hidden" name="termo" value="{{termo.id}}" >
            <input type="hidden" name="modalidade" value="{{modalidade}}" >
            <input type="hidden" name="agilis" value="{{agilis}}" >
            <input type="hidden" name="doado" value="{{doado}}" >
            <input type="hidden" name="localizado" value="{{localizado}}" >
            <input type="hidden" name="numero_fmusp" value="{{numero_fmusp}}" >
            <input type="hidden" name="ver_numero_fmusp" value="{{ver_numero_fmusp|default:""}}" >
            {%for m in marca%}
                <input type="hidden" name="marca" value="{{m}}" >
            {%endfor%}
            <div title="Imprimir" class="btn_print">
               <input type="submit" title="Versão para impressão" class="btn_print" name="acao" value="1"  />
            </div>
        </form>
    </div>
{% endif %}
<div id="div_filtro">
    <fieldset>
        <legend>Filtro</legend>
    	<form method="GET" id="form_filtro">
        	<div>
        		<div>
        		    <label for="id_termo">Termo de outorga*:</label>
        		    <select name="termo" id="id_termo">
        		      <option value="0">Todos</option>
        		      {% for t in filtro_termos %}
        		         <option value="{{ t.id }}" {% if t.id == termo.id%}selected{% endif %}>{{ t }}</option>
        		      {% endfor %}
        		    </select>
        		</div>
        		<div>
        		    <label for="id_marca">Marca</label>
        		    <select name="marca" id="id_marca" multiple size=4>
        		        <option value="0" {% if '0' in marca%}selected{% endif %}>Todos</option>
        		        {% for m in filtro_marcas %}
        		           <option value="{{ m.id }}" {% if m.id|safe in marca%}selected{% endif %}>{{ m }}</option>
        		        {% endfor %}
        		    </select>
        		</div>
        		
        		<div>
        		    <label for="id_modalidade">Modalidade</label>
        		    <select name="modalidade" id="id_modalidade">
        		        <option value="0" {% if '0' == modalidade%}selected{% endif %}>Todos</option>
        		        <option value="1" {% if '1' == modalidade%}selected{% endif %}>Material permanente</option>
        		        <option value="2" {% if '2' == modalidade%}selected{% endif %}>Material de consumo</option>
        		    </select>
        		</div>
        	</div>
        	<div>
        		<div>
        		    <label for="id_agilis">Têm Agilis</label>
        		    <select name="agilis" id="id_agilis">
        		         <option value="-" {% if '-' == agilis%}selected{% endif %}>Todos</option>
        		         <option value="0" {% if '0' == agilis%}selected{% endif %}>Não</option>
        		         <option value="1" {% if '1' == agilis%}selected{% endif %}>Sim</option>
        		    </select>
        		</div>
        		<div>
        		    <label for="id_doado">Doado por processo oficial</label>
        		    <select name="doado" id="id_doado">
        		         <option value="2" {% if '2' == doado%}selected{% endif %}>Todos</option>
        		         <option value="0" {% if '0' == doado%}selected{% endif %}>Não doados</option>
        		         <option value="1" {% if '1' == doado%}selected{% endif %}>Doados</option>
        		    </select>
        		</div>
        		<div>
        		    <label for="id_localizado">Patrimônio localizado</label>
        		    <select name="localizado" id="id_localizado">
        		         <option value="2" {% if '2' == localizado%}selected{% endif %}>Todos</option>
        		         <option value="0" {% if '0' == localizado%}selected{% endif %}>Não localizados</option>
        		         <option value="1" {% if '1' == localizado%}selected{% endif %}>Localizados</option>
        		    </select>
        		</div>
        		<div>
        		    <label for="id_numero_fmusp">Com identificação do patrimônio oficial</label>
        		    <select name="numero_fmusp" id="id_numero_fmusp">
        		         <option value="2" {% if '2' == numero_fmusp%}selected{% endif %}>Todos</option>
        		         <option value="0" {% if '0' == numero_fmusp%}selected{% endif %}>Não</option>
        		         <option value="1" {% if '1' == numero_fmusp%}selected{% endif %}>Sim</option>
        		    </select>
        		</div>
        		<div>
        		    <label for="id_ver_numero_fmusp">Apresenta patrimônio oficial no relatório</label>
        		    <input type="checkbox" name="ver_numero_fmusp" id="id_ver_numero_fmusp"  {% if 'on' in ver_numero_fmusp%}checked{% endif %} />
        		</div>
        	</div>
        	<br />
        	<div id="div_submit">
        	    <input type="submit" value="Enviar">
        	</div>
    	</form>
     </fieldset>
</div>

{% if termos %}
    <p style="clear:both;"></p>
    <table id="tbl_conteudo" border="0" repeat="1" cellpadding="5">
        <tr>
            {% if ver_numero_fmusp %}
                <th>Patrimônio oficial</th>
            {% endif %}
            <th class="th_nf">NF</th>
            <th colspan="2" class="th_descricao">Descrição - complemento</th>
            <th class="th_valor">Valor</th>
            <th class="th_marca">Marca</th>
            <th class="th_ns">NS</th>
            <th class="th_estado">Estado</th>
            <th class="th_localizacao">Localização</th>
            <th class="th_posicao">Posição</th>
        </tr>
        {% for t in termos %}
            {% for tp in t.tipos %}
               {% for pg in tp.pagamentos %}
                  <tr>
                    {% if ver_numero_fmusp %}
                        <td></td>
                    {% endif %}
                    <td><a href="{% url 'admin:protocolo_protocolo_change' pg.pg.protocolo.id %}">{{ pg.pg.protocolo.num_documento }}</a></td>
                    <td colspan="9"></td>
                  </tr>
                  {% for p in pg.patrimonios %}
                     <tr>
                        {% if ver_numero_fmusp %}
                            <td>{{ p.numero_fmusp|default_if_none:"" }}</td>
                        {% endif %}
                        <td></td>
                        <td colspan="2"><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{% if p.equipamento %}[{{ p.equipamento.tipo }}] {% endif %}{{ p.descricao }} - {{ p.complemento|default:"" }}</a></td>
                        <td>{{ p.valor }}</td>
                        <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ p.equipamento.entidade_fabricante.sigla }}</a> </td>
                        <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ p.ns }}</a></td>
                        {% with p.historico_atual as historico_atual %}  
                        <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ historico_atual.estado }}</a></td>
                        <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ historico_atual.endereco }}</a></td>
                        <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ historico_atual.posicao|default_if_none:"" }}</a></td>
                        {% endwith %}
                     </tr>
                     {% if not numero_fmusp %}
                       {% for pf in p.contido.all %}
                        <tr>
                            {% if ver_numero_fmusp %}
                                <td></td>
                            {% endif %}
                            <td></td>
                            <td width="10px"></td>
                            <td>{% if pf.equipamento %}[{{ pf.equipamento.tipo }}] {% endif %}{{ pf.descricao }} - {{ pf.complemento|default:"" }}</td>
                            <td>{{ pf.valor }}</td>
                            <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ pf.equipamento.entidade_fabricante.sigla }}</a></td>
                            <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ pf.ns }}</td>
                            <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ pf.historico_atual.estado }}</td>
                            <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ pf.historico_atual.endereco }}</td>
                            <td><a href="{% url 'admin:patrimonio_patrimonio_change' p.id %}">{{ pf.historico_atual.posicao|default_if_none:"" }}</td>
                        </tr>
                       {% endfor %}
                     {% endif %}
                  {% endfor %}
               {% endfor %}
            {% endfor %}
        {% endfor %}
    </table>
{% else %}
    <table border="0" repeat="1" cellpadding="5">
        <tr><td>Não foram encontrados dados para a exibição.</td></tr>
    </table>
{% endif %}
{% endblock %}