identificacao/urls.py
# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django.conf.urls import patterns

urlpatterns = patterns('identificacao.views',
                       (r'escolhe_entidade$', 'ajax_escolhe_entidade'),
                       (r'escolhe_endereco$', 'ajax_escolhe_endereco'),
                       (r'escolhe_entidade_filhos$', 'ajax_escolhe_entidade_filhos'),
                       (r'relatorios/arquivos$', 'arquivos_entidade'),
                       (r'agenda/(?P<pdf>[a-z]+)/(?P<tipo>\d+)$', 'agenda'),
                       (r'agenda/(?P<pdf>[a-z]+)$', 'agenda'),
                       (r'agenda/(?P<tipo>\d+)/$', 'agenda'),
                       (r'agenda$', 'agenda'),
                       (r'acessos/terremark$', 'acessos_terremark'),
                       (r'ecossistema/(?P<tipo>[a-z]+)$', 'planilha_ecossistema'),
                       )

identificacao/forms.py
# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

from django import forms
from django.utils.html import mark_safe
import re

from identificacao.models import Contato, Endereco, Entidade, EnderecoDetalhe,\
    Identificacao, Acesso


EMAIL_RE = re.compile(
    r"(^[-!#$%&'*+/=?^_`{}|~0-9A-Z]+(\.[-!#$%&'*+/=?^_`{}|~0-9A-Z]+)*"  # dot-atom
    r'|^"([\001-\010\013\014\016-\037!#-\[\]-\177]|\\[\001-\011\013\014\016-\177])*"'  # quoted-string
    r')@(?:[A-Z0-9-]+\.)+[A-Z]{2,6}$', re.IGNORECASE)  # domain


# Faz a validação de um e-mmail
def is_valid_email(value):
    return EMAIL_RE.search(value)


class ContatoAdminForm(forms.ModelForm):

    """
    A função 'clean_email' identifica cada e-mail do campo 'email' e verifica se eles são validos.
    """

    # Define o modelo
    class Meta:
        model = Contato
        fields = ['primeiro_nome', 'ultimo_nome', 'ativo', 'email', 'tel', 'documento']

    # Verifica se os e-mail são válidos.
    def clean_email(self):

        value = self.cleaned_data['email']

        if not value:
            return value
        emails = [e.strip() for e in value.split(',')]
        for email in emails:
            if not is_valid_email(email):
                raise forms.ValidationError(u'%s não é um e-mail válido.' % email)

        # Always return the cleaned data.
        return value


class EnderecoAdminForm(forms.ModelForm):

    entidade = forms.ModelChoiceField(Entidade.objects.all(), required=False,
                                      widget=forms.Select(attrs={'onchange': 'ajax_select_endereco2();'}))

    class Meta:
        model = Endereco
        fields = ['entidade', 'rua', 'num', 'compl', 'cep', 'bairro', 'cidade', 'estado', 'pais']

    class Media:
        js = ('/site-media/js/selects.js', '/site-media/js/identificacao.js')


class EnderecoDetalheAdminForm(forms.ModelForm):

    # Campo de filtro por Entidade para reduzir a seleção do campo Endereço
    entidade = forms.ModelChoiceField(Entidade.objects.all(), required=False,
                                      widget=forms.Select(attrs={'onchange': 'ajax_select_endereco2();',
                                                                 'class': 'auxiliary'}))

    def __init__(self, *args, **kwargs):
        super(EnderecoDetalheAdminForm, self).__init__(*args, **kwargs)

        # Adicionando link para o label do campo de Tipo de Conector
        self.fields['endereco'].label = mark_safe('<a href="#" onclick="window.open(\'/admin/identificacao/endereco/\''
                                                  '+$(\'#id_endereco\').val() + \'/\', \'_blank\');return true;">%s</a>'
                                                  % self.fields['endereco'].label)
        self.fields['detalhe'].label = mark_safe('<a href="#" onclick="window.open(\'/admin/identificacao/endereco'
                                                 'detalhe/\'+$(\'#id_detalhe\').val() + \'/\', \'_blank\');return true;'
                                                 '">%s</a>' % self.fields['detalhe'].label)

        # Populando campos
        entidade_ids = Endereco.objects.all().values('entidade')

        self.fields['entidade'].choices = [('', '---------')] + \
                                          [(p.id, p.__unicode__()) for p in Entidade.objects.all().filter(id__in=entidade_ids)]
        self.fields['endereco'].choices = [('', '---------')] + \
                                          [(p.id, p.__unicode__()) for p in Endereco.objects.all().select_related('entidade')]
        self.fields['detalhe'].choices = [('', '---------')] + \
                                         [(p.id, p.__unicode__()) for p in EnderecoDetalhe.objects.all()
                                          .select_related('detalhe__endereco__entidade__sigla', 'endereco__entidade__sigla')]

    def clean(self):
        cleaned_data = self.cleaned_data
        endereco = cleaned_data.get('endereco')
        detalhe = cleaned_data.get('detalhe')

        if endereco is None and detalhe is None:
            raise forms.ValidationError(u'Endereço e detalhe do endereço não podem ser ambos nulos')
        elif endereco and detalhe:
            raise forms.ValidationError(u'Endereço e detalhe do endereço não podem ser ambos utilizados')

        return cleaned_data

    class Meta:
        model = EnderecoDetalhe
        fields = ['entidade', 'endereco', 'detalhe', 'tipo', 'complemento']

    class Media:
        js = ('js/selects.js',)


class AcessoAdminForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(AcessoAdminForm, self).__init__(*args, **kwargs)

        self.fields['identificacao'].choices = [('', '---------')] + \
                                               [(p.id, p.__unicode__()) for p in Identificacao.objects.all()
                                                .select_related('endereco__entidade', 'contato')
                                                .order_by('endereco__entidade__sigla', 'area', 'contato__primeiro_nome')]

        self.fields['detalhe'].choices = [(p.id, p.__unicode__()) for p in EnderecoDetalhe.objects.all()
                                          .select_related('endereco__entidade', 'detalhe__endereco__entidade')]

    class Meta:
        model = Acesso
        fields = ['identificacao', 'niveis', 'liberacao', 'encerramento', 'obs', 'detalhe']


class EnderecoDetalheInlineAdminForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(EnderecoDetalheInlineAdminForm, self).__init__(*args, **kwargs)

        self.fields['detalhe'].choices = [('', '---------')] + \
                                         [(p.id, p.__unicode__()) for p in EnderecoDetalhe.objects.all()
                                          .select_related('endereco__entidade', 'detalhe__endereco__entidade')]

    class Meta:
        model = EnderecoDetalhe
        fields = ['tipo', 'complemento', 'detalhe', 'mostra_bayface']

identificacao/templates/identificacao/acessos.html
{% extends "admin/base_site.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% block content %}
<form method="GET">
<label for="id_entidade">Entidade</label>:
<select name="entidade" id="id_entidade">
  {% for e in entidades %}
     <option value="{{ e.id }}">{{ e }}</option>
  {% endfor %}
</select>
<input type="submit" value="Enviar">
</form>
{% endblock %}

identificacao/templates/identificacao/agenda.html
{% extends "admin/base_site.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% load proto_tags %}
{% load i18n %}
{% block extrahead %}
<style type="text/css">
.tabnav {
        width: 100%;
        height: 30px;
        margin: 0 auto;
        border-bottom:solid 1px #9fc3e5;
}
.tabnav ul{margin:10px 20px 0 20px;}
.tabnav ul li {
        display:block;
        float:left;
        margin:0 1px;
        border-top-left-radius:5px;
        border-top-right-radius:5px;
        -moz-border-top-left-radius:5px;
        -moz-border-top-right-radius:5px;
        -webkit-border-top-left-radius:5px;
        -webkit-border-top-right-radius:5px;
        }

.tabnav ul li span {
        background: #0015b0;
        color: #fff;
        min-width:15px;
        font-size:12px;
        font-weight:bold;
        padding:5px;
        text-align:center;
        line-height:20px;
        float:left;
}
        
.tabnav ul li a {
        float:left;
        background: #9fc3e5;
        /*background: #9fc3e5 url("tab.jpg") top left no-repeat;*/
        text-decoration: none;
        line-height:20px;
        color: #fff;
        font-size: 12px;
        font-weight: bold;
        display: block;
        min-width: 15px;
        height: 20px;
        margin:0;
        padding:5px;
        text-align: center;
}

.tabnav ul li a:hover{background:#6699cc;}

.tabnav-click {background:#464646; color:#ff0000;}
</style>
{% endblock %}
{% block breadcrumbs %}
    <div class="breadcrumbs">Você está em: 
      <a href="../../">{% trans "Home" %}</a> &rsaquo; 
      <a href="{% url 'identificacao.views.agenda' %}">Agenda</a>
    </div>
{% endblock %}
{% block content %}
  <h1>Agenda</h1>
  <br>
  <div id="report_toolbar">
      <form action="{% url 'identificacao.views.agenda' 'pdf' tipo %}" method="GET" id="id_form_recurso_pdf">
          <input type="hidden" name="agenda" value="{{ agenda }}" />
          <div title="Imprimir" class="btn_print">
             <input type="submit" title="Versão para impressão" class="btn_print" value="" />
          </div>
      </form>
  </div>

  <div class="tabnav">
    <ul>
        {% for t in tipos %}
        <li>{% if t.id == tipo %}<span>{{ t.nome }}</span>{% else %}<a href="{% url 'identificacao.views.agenda' t.id %}?agenda={{ agenda }}">{{ t.nome }}</a>{% endif %}</li>
        {% endfor %}
    </ul>
  </div>

  <table>
  {% for e in entidades %}
    <tr><td width="20%">{% if not e.filho %}{% if e.entidade.url %}<a href="{{ e.entidade.url }}">{{ e.entidade.sigla }}</a>{% else %}{{ e.entidade.sigla }}{% endif %}{% endif %}</td><td colspan="3">{% if e.filho %}<span style="font-weight:bold;">{{ e.entidade.sigla }}</span> - {% endif %}{{ e.entidade.nome }}</td></tr>
    {% for a in e.areas %}
      <tr><td></td><td colspan="3">{{ a.area }}</td></tr>
      {% for c in a.contatos %}
         <tr><td></td><td width="15%"></td><td>{% if c.contato.ativo %}<b>{{ c.contato.nome }}</b>{% else %}<span style="color:red;">{{ c.contato.nome }}</span>{% endif %} ({{ c.contato.email }})</td><td>{{ c.funcao }}</td></tr>
         <tr><td></td><td></td><td>{{ c.endereco.logradouro }} - CEP: {{ c.endereco.cep }}</td></tr>
         <tr><td></td><td></td><td>{{ c.endereco.bairro}} - {{ c.endereco.cidade }} - {{ c.endereco.estado }}</td></tr>
         <tr><td></td><td></td><td>{{ c.contato.tel }}</td></tr>
      {% endfor %}
    {% endfor %}
  {% endfor %}
  </table>
{% endblock %}

identificacao/templates/identificacao/agendas.html
{% extends "admin/base_site.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% load proto_tags %}
{% load i18n %}
{% block breadcrumbs %}
    <div class="breadcrumbs">Você está em: 
      <a href="../../">{% trans "Home" %}</a> &rsaquo; 
      <a href="{% url 'identificacao.views.agenda' %}">Agenda</a>
    </div>
{% endblock %}
{% block content %}
<div id="report_title">
    <h1>Agenda</h1>
</div>

<div id="div_filtro">
    <fieldset>
        <legend>Filtro</legend>
        <p>Selecione uma agenda:</p>
        <form action="" method="GET">
            <label for="id_agenda">Agenda:</label>
            <select name="agenda" id="id_agenda">
                {% for a in agendas %}
                    <option value="{{ a.id }}">{{ a.nome }}</option>
                {% endfor %}
            </select>
            <input type="submit" value="Escolher" />
        </form>
    </fieldset>
</div>


    
{% endblock %}

identificacao/templates/identificacao/arquivos_entidade.html
{% extends "admin/base_site.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% load proto_tags %}
{% load i18n %}
{% block breadcrumbs %}
    <div class="breadcrumbs">Você está em: 
      <a href="../../">{% trans "Home" %}</a> &rsaquo; 
      <a href="{% url 'identificacao.views.arquivos_entidade' %}">Documentos por entidade</a>
    </div>
{% endblock %}
{% block content %}
<h1 repeat="1">Documentos por entidade</h1>

{% if entidades %}
    <table border="0" cellpadding="5">
        {% for e in entidades %}
            <tr><td>{{ e.sigla }}</td></tr>
            {% for a in e.arquivoentidade_set.all %}
                <tr><td></td><td>{{ a.data }}</td><td>{{ a.tipo }}</td><td><a href="{{ a.arquivo.url }}">{{ a.arquivo.name }}</a></td></tr>
            {% endfor %}
        {% endfor %}
    </table>
{% else %}
    <table border="0" repeat="1">
        <tr><td><br><br>Não foram encontrados dados para a exibição.</td></tr>
    </table>
{% endif %}

{% endblock %}

identificacao/templates/identificacao/ecossistema.html
{% extends "admin/base_site.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% load i18n %}
{% block breadcrumbs %}
    <div class="breadcrumbs">Você está em: 
      <a href="../../">{% trans "Home" %}</a> &rsaquo; 
      <a href="{% url 'identificacao.views.planilha_ecossistema' 'par'%}">Ecossistema</a>
    </div>
{% endblock %}
{% block extrahead %}
<style type="text/css">
.tabnav {
        width: 100%;
        height: 30px;
        margin: 0 auto;
        border-bottom:solid 1px #9fc3e5;
}
.tabnav ul{margin:10px 20px 0 20px;}
.tabnav ul li {
        display:block;
        float:left;
        margin:0 1px;
        border-top-left-radius:5px;
        border-top-right-radius:5px;
        -moz-border-top-left-radius:5px;
        -moz-border-top-right-radius:5px;
        -webkit-border-top-left-radius:5px;
        -webkit-border-top-right-radius:5px;
        }

.tabnav ul li span {
        background: #0015b0;
        color: #fff;
        min-width:15px;
        font-size:12px;
        font-weight:bold;
        padding:5px;
        text-align:center;
        line-height:20px;
        float:left;
}

.tabnav ul li a {
        float:left;
        background: #9fc3e5;
        /*background: #9fc3e5 url("tab.jpg") top left no-repeat;*/
        text-decoration: none;
        line-height:20px;
        color: #fff;
        font-size: 12px;
        font-weight: bold;
        display: block;
        min-width: 15px;
        height: 20px;
        margin:0;
        padding:5px;
        text-align: center;
}

.tabnav ul li a:hover{background:#6699cc;}

.tabnav-click {background:#464646; color:#ff0000;}
</style>
{% endblock %}

identificacao/templates/identificacao/ecossistema_par.html
{% extends "identificacao/ecossistema.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% block content %}
<h1>Ecossistema</h1>

<div class="tabnav">
    <ul>
        <li><span>Participantes</span></li>
        <li><a href="{% url 'identificacao.views.planilha_ecossistema' 'tic' %}">TICs</a></li>
    </ul>
</div>
{% if ec %}
    <table border="1" style="width:3000px;">
        <tr>
            <th>Número</th>
            <th>Participante</th>
            <th>Nome completo da entidade participante</th>
            <th>Incentivar a dar palestra?</th>
            <th>Monitorar o convite?</th>
            <th>Responsável técnico</th>
            <th>Cargo</th>
            <th>E-mail</th>
            <th>Endereço comercial</th>
            <th>CEP</th>
            <th>Cidade</th>
            <th>UF</th>
            <th>Telefone</th>
            <th>Data de envio do e-mail</th>
            <th>Data da resposta ao e-mail</th>
            <th>Vai dar palestra?</th>
            <th>Palestrante</th>
            <th>Tema</th>
            <th>Temas adicionais sugeridos</th>
            <th>Data de envio postal</th>
            <th>Inscrições solicitadas</th>
            <th>Inscrições aceitas</th>
            <th>Comentários</th>
            <th>Quer hotel?</th>
        </tr>
        {% for e in ec %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ e.identificacao.endereco.entidade.sigla }}</td>
                <td>{{ e.identificacao.endereco.entidade.nome }}</td>
                <td>{% if e.incentivo %}Sim{% else %}Não{% endif %}</td>
                <td>{% if e.monitora %}Sim{% else %}Não{% endif %}</td>
                <td>{{ e.identificacao.contato.nome }}</td>
                <td>{{ e.identificacao.funcao }}</td>
                <td>{{ e.identificacao.contato.email }}</td>
                <td>{{ e.identificacao.endereco.logradouro }}</td>
                <td>{{ e.identificacao.endereco.cep }}</td>
                <td>{{ e.identificacao.endereco.cidade }}</td>
                <td>{{ e.identificacao.endereco.estado }}</td>
                <td>{{ e.identificacao.contato.tel }}</td>
                <td>{{ e.data_envio|default_if_none:'' }}</td>
                <td>{{ e.data_resposta|default_if_none:'' }}</td>
                <td>{% if e.dar_palestra %}Sim{% else %}Não{% endif %}</td>
                <td>{{ e.palestrante }}</td>
                <td>{{ e.tema }}</td>
                <td>{{ e.temas_adicionais }}</td>
                <td>{{ e.data_envio_postal|default_if_none:'' }}</td>
                <td>{{ e.inscricoes_solicitadas|default_if_none:0 }}</td>
                <td>{{ e.inscricoes_aceitas|default_if_none:0 }}</td>
                <td>{{ e.comentarios }}</td>
                <td>{% if e.hotel %}Sim{% else %}Não{% endif %}</td>
            </tr>
        {% endfor %}
    </table>
{% else %}
    <table border="0" repeat="1">
        <tr><td><br><br>Não foram encontrados dados para a exibição.</td></tr>
    </table>
{% endif %}

{% endblock %}

identificacao/templates/identificacao/ecossistema_tic.html
{% extends "identificacao/ecossistema.html" %}
{% comment %}
This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.
{% endcomment %}
{% block content %}
<h1>Ecossistema</h1>

<div class="tabnav">
    <ul>
        <li><a href="{% url 'identificacao.views.planilha_ecossistema' 'par' %}">Participantes</a></li>
        <li><span>TICs</span></li>
    </ul>
</div>
{% if ec %}
    <table border="1" style="width:3000px;">
        <tr>
            <th>Número</th>
            <th>Empresa</th>
            <th>Nome completo da empresa</th>
            <th>Contato para patrocínio?</th>
            <th>VIP?</th>
            <th>Chaser</th>
            <th>Data de envio do e-mail</th>
            <th>E-mail</th>
            <th>Nome destinatário e-mail</th>
            <th>Cargo</th>
            <th>Data de envio postal</th>
            <th>Nome destinatário carta</th><th>Cargo</th><th>Recebeu e-mail?</th><th>Endereço comercial</th><th>CEP</th><th>Cidade</th><th>UF</th><th>Telefone</th><th>Vai patrocinar?</th><th>Inscrições pagas</th><th>Vai dar palestra?</th><th>Tema</th></tr>
        {% for e in ec %}
            <tr><td>{{ forloop.counter }}</td><td>{{ e.identificacao.endereco.entidade.sigla }}</td><td>{{ e.identificacao.endereco.entidade.nome }}</td><td>{% if e.contato_pat %}Sim{% else %}Não{% endif %}</td><td>{% if e.vip %}Sim{% else %}Não{% endif %}</td><td>{{ e.chaser }}</td><td>{{ e.data_envio|default_if_none:'' }}</td><td>{{ e.identificacao.contato.email }}</td><td>{{ e.identificacao.contato.nome }}</td><td>{{ e.identificacao.funcao }}</td><td>{{ e.data_envio_postal|default_if_none:'' }}</td><td>{{ e.identificacao.contato.nome }}</td><td>{{ e.identificacao.funcao }}</td><td></td><td>{{ e.identificacao.endereco.logradouro }}</td><td>{{ e.identificacao.endereco.cep }}</td><td>{{ e.identificacao.endereco.cidade }}</td><td>{{ e.identificacao.endereco.estado }}</td><td>{{ e.identificacao.contato.tel }}</td><td>{{ e.vai_pat }}</td><td>{{ e.inscricoes_aceitas|default_if_none:0 }}</td><td>{% if e.dar_palestra %}Sim{% else %}Não{% endif %}</td><td>{{ e.tema }}</td></tr>
        {% endfor %}
    </table>
{% else %}
    <table border="0" repeat="1">
        <tr><td><br><br>Não foram encontrados dados para a exibição.</td></tr>
    </table>
{% endif %}

{% endblock %}